<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       http://themographics.com
 * @since      1.0
 *
 * @package    Soccer
 * @subpackage Soccer/admin
 */
/**
 * Icons List
 * @return 
 */
if (!function_exists('soccer_prepare_icons')) {

    function soccer_prepare_icons() {
        $icon = array(
            '' => 'Ban',
            'fa fa-adjust' => 'Adjust',
            'fa fa-adn' => 'Adn',
            'fa fa-align-center' => 'Align Center',
            'fa fa-align-justify' => 'Align Justify',
            'fa fa-align-left' => 'Align Left',
            'fa fa-align-right' => 'Align Right',
            'fa fa-ambulance' => 'Ambulance',
            'fa fa-anchor' => 'Anchor',
            'fa fa-android' => 'Android',
            'fa fa-angle-double-down' => 'Angle Double Down',
            'fa fa-angle-double-left' => 'Angle Double Left',
            'fa fa-angle-double-right' => 'Angle Double Right',
            'fa fa-angle-double-up' => 'Angle Double Up',
            'fa fa-angle-down' => 'Angle Down',
            'fa fa-angle-left' => 'Angle Left',
            'fa fa-angle-right' => 'Angle Right',
            'fa fa-angle-up' => 'Angle Up',
            'fa fa-apple' => 'Apple',
            'fa fa-archive' => 'Archive',
            'fa fa-arrow-circle-down' => 'Arrow Circle Down',
            'fa fa-arrow-circle-left' => 'Arrow Circle Left',
            'fa fa-arrow-circle-o-down' => 'Arrow Circle O Down',
            'fa fa-arrow-circle-o-left' => 'Arrow Circle O Left',
            'fa fa-arrow-circle-o-right' => 'Arrow Circle O Right',
            'fa fa-arrow-circle-o-up' => 'Arrow Circle O Up',
            'fa fa-arrow-circle-right' => 'Arrow Circle Right',
            'fa fa-arrow-circle-up' => 'Arrow Circle Up',
            'fa fa-arrow-down' => 'Arrow Down',
            'fa fa-arrow-left' => 'Arrow Left',
            'fa fa-arrow-right' => 'Arrow Right',
            'fa fa-arrows' => 'Arrows',
            'fa fa-arrows-alt' => 'Arrows Alt',
            'fa fa-arrows-h' => 'Arrows H',
            'fa fa-arrows-v' => 'Arrows V',
            'fa fa-arrow-up' => 'Arrow Up',
            'fa fa-asterisk' => 'Asterisk',
            'fa fa-automobile' => 'Automobile',
            'fa fa-backward' => 'Backward',
            'fa fa-bank' => 'Bank',
            'fa fa-bar-chart-o' => 'Bar Chart O',
            'fa fa-barcode' => 'Barcode',
            'fa fa-bars' => 'Bars',
            'fa fa-bed' => 'Bed',
            'fa fa-bed' => 'Hotel',
            'fa fa-beer' => 'Beer',
            'fa fa-behance' => 'Behance',
            'fa fa-behance-square' => 'Behance Square',
            'fa fa-bell' => 'Bell',
            'fa fa-bell-o' => 'Bell O',
            'fa fa-bitbucket' => 'Bitbucket',
            'fa fa-bitbucket-square' => 'Bitbucket Square',
            'fa fa-bitcoin' => 'Bitcoin',
            'fa fa-bold' => 'Bold',
            'fa fa-bolt' => 'Bolt',
            'fa fa-bomb' => 'Bomb',
            'fa fa-book' => 'Book',
            'fa fa-bookmark' => 'Bookmark',
            'fa fa-bookmark-o' => 'Bookmark O',
            'fa fa-briefcase' => 'Briefcase',
            'fa fa-btc' => 'Btc',
            'fa fa-bug' => 'Bug',
            'fa fa-building' => 'Building',
            'fa fa-building-o' => 'Building O',
            'fa fa-bullhorn' => 'Bullhorn',
            'fa fa-bullseye' => 'Bullseye',
            'fa fa-buysellads' => 'Buysellads',
            'fa fa-cab' => 'Cab',
            'fa fa-calendar' => 'Calendar',
            'fa fa-calendar-o' => 'Calendar O',
            'fa fa-camera' => 'Camera',
            'fa fa-camera-retro' => 'Camera Retro',
            'fa fa-car' => 'Car',
            'fa fa-caret-down' => 'Caret Down',
            'fa fa-caret-left' => 'Caret Left',
            'fa fa-caret-right' => 'Caret Right',
            'fa fa-caret-square-o-down' => 'Caret Square O Down',
            'fa fa-caret-square-o-left' => 'Caret Square O Left',
            'fa fa-caret-square-o-right' => 'Caret Square O Right',
            'fa fa-caret-square-o-up' => 'Caret Square O Up',
            'fa fa-caret-up' => 'Caret Up',
            'fa fa-cart-arrow-down' => 'Cart Arrow Down',
            'fa fa-cart-plus' => 'Cart Plus',
            'fa fa-certificate' => 'Certificate',
            'fa fa-chain' => 'Chain',
            'fa fa-chain-broken' => 'Chain Broken',
            'fa fa-check' => 'Check',
            'fa fa-check-circle' => 'Check Circle',
            'fa fa-check-circle-o' => 'Check Circle O',
            'fa fa-check-square' => 'Check Square',
            'fa fa-check-square-o' => 'Check Square O',
            'fa fa-chevron-circle-down' => 'Chevron Circle Down',
            'fa fa-chevron-circle-left' => 'Chevron Circle Left',
            'fa fa-chevron-circle-right' => 'Chevron Circle Right',
            'fa fa-chevron-circle-up' => 'Chevron Circle Up',
            'fa fa-chevron-down' => 'Chevron Down',
            'fa fa-chevron-left' => 'Chevron Left',
            'fa fa-chevron-right' => 'Chevron Right',
            'fa fa-chevron-up' => 'Chevron Up',
            'fa fa-child' => 'Child',
            'fa fa-circle' => 'Circle',
            'fa fa-circle-o' => 'Circle O',
            'fa fa-circle-o-notch' => 'Circle O Notch',
            'fa fa-circle-thin' => 'Circle Thin',
            'fa fa-clipboard' => 'Clipboard',
            'fa fa-clock-o' => 'Clock O',
            'fa fa-cloud' => 'Cloud',
            'fa fa-cloud-download' => 'Cloud Download',
            'fa fa-cloud-upload' => 'Cloud Upload',
            'fa fa-cny' => 'Cny',
            'fa fa-code' => 'Code',
            'fa fa-code-fork' => 'Code Fork',
            'fa fa-codepen' => 'Codepen',
            'fa fa-coffee' => 'Coffee',
            'fa fa-cog' => 'Cog',
            'fa fa-cogs' => 'Cogs',
            'fa fa-columns' => 'Columns',
            'fa fa-comment' => 'Comment',
            'fa fa-comment-o' => 'Comment O',
            'fa fa-comments' => 'Comments',
            'fa fa-comments-o' => 'Comments O',
            'fa fa-compass' => 'Compass',
            'fa fa-compress' => 'Compress',
            'fa fa-connectdevelop' => 'Connectdevelop',
            'fa fa-copy' => 'Copy',
            'fa fa-credit-card' => 'Credit Card',
            'fa fa-crop' => 'Crop',
            'fa fa-crosshairs' => 'Crosshairs',
            'fa fa-css3' => 'Css3',
            'fa fa-cube' => 'Cube',
            'fa fa-cubes' => 'Cubes',
            'fa fa-cut' => 'Cut',
            'fa fa-cutlery' => 'Cutlery',
            'fa fa-dashboard' => 'Dashboard',
            'fa fa-dashcube' => 'Dashcube',
            'fa fa-database' => 'Database',
            'fa fa-dedent' => 'Dedent',
            'fa fa-delicious' => 'Delicious',
            'fa fa-desktop' => 'Desktop',
            'fa fa-deviantart' => 'Deviantart',
            'fa fa-diamond' => 'Diamond',
            'fa fa-digg' => 'Digg',
            'fa fa-dollar' => 'Dollar',
            'fa fa-dot-circle-o' => 'Dot Circle O',
            'fa fa-download' => 'Download',
            'fa fa-dribbble' => 'Dribbble',
            'fa fa-dropbox' => 'Dropbox',
            'fa fa-drupal' => 'Drupal',
            'fa fa-edit' => 'Edit',
            'fa fa-eject' => 'Eject',
            'fa fa-ellipsis-h' => 'Ellipsis H',
            'fa fa-ellipsis-v' => 'Ellipsis V',
            'fa fa-empire' => 'Empire',
            'fa fa-envelope' => 'Envelope',
            'fa fa-envelope-o' => 'Envelope O',
            'fa fa-envelope-square' => 'Envelope Square',
            'fa fa-eraser' => 'Eraser',
            'fa fa-eur' => 'Eur',
            'fa fa-euro' => 'Euro',
            'fa fa-exchange' => 'Exchange',
            'fa fa-exclamation' => 'Exclamation',
            'fa fa-exclamation-circle' => 'Exclamation Circle',
            'fa fa-exclamation-triangle' => 'Exclamation Triangle',
            'fa fa-expand' => 'Expand',
            'fa fa-external-link' => 'External Link',
            'fa fa-external-link-square' => 'External Link Square',
            'fa fa-eye' => 'Eye',
            'fa fa-eye-slash' => 'Eye Slash',
            'fa fa-facebook' => 'Facebook',
            'fa fa-facebook-official' => 'Facebook Official',
            'fa fa-facebook-square' => 'Facebook Square',
            'fa fa-fast-backward' => 'Fast Backward',
            'fa fa-fast-forward' => 'Fast Forward',
            'fa fa-fax' => 'Fax',
            'fa fa-female' => 'Female',
            'fa fa-fighter-jet' => 'Fighter Jet',
            'fa fa-file' => 'File',
            'fa fa-file-archive-o' => 'File Archive O',
            'fa fa-file-audio-o' => 'File Audio O',
            'fa fa-file-code-o' => 'File Code O',
            'fa fa-file-excel-o' => 'File Excel O',
            'fa fa-file-image-o' => 'File Image O',
            'fa fa-file-movie-o' => 'File Movie O',
            'fa fa-file-o' => 'File O',
            'fa fa-file-pdf-o' => 'File Pdf O',
            'fa fa-file-photo-o' => 'File Photo O',
            'fa fa-file-picture-o' => 'File Picture O',
            'fa fa-file-powerpoint-o' => 'File Powerpoint O',
            'fa fa-files-o' => 'Files O',
            'fa fa-file-sound-o' => 'File Sound O',
            'fa fa-file-text' => 'File Text',
            'fa fa-file-text-o' => 'File Text O',
            'fa fa-file-video-o' => 'File Video O',
            'fa fa-file-word-o' => 'File Word O',
            'fa fa-file-zip-o' => 'File Zip O',
            'fa fa-film' => 'Film',
            'fa fa-filter' => 'Filter',
            'fa fa-fire' => 'Fire',
            'fa fa-fire-extinguisher' => 'Fire Extinguisher',
            'fa fa-flag' => 'Flag',
            'fa fa-flag-checkered' => 'Flag Checkered',
            'fa fa-flag-o' => 'Flag O',
            'fa fa-flash' => 'Flash',
            'fa fa-flask' => 'Flask',
            'fa fa-flickr' => 'Flickr',
            'fa fa-floppy-o' => 'Floppy O',
            'fa fa-folder' => 'Folder',
            'fa fa-folder-o' => 'Folder O',
            'fa fa-folder-open' => 'Folder Open',
            'fa fa-folder-open-o' => 'Folder Open O',
            'fa fa-font' => 'Font',
            'fa fa-forumbee' => 'Forumbee',
            'fa fa-forward' => 'Forward',
            'fa fa-foursquare' => 'Foursquare',
            'fa fa-frown-o' => 'Frown O',
            'fa fa-gamepad' => 'Gamepad',
            'fa fa-gavel' => 'Gavel',
            'fa fa-gbp' => 'Gbp',
            'fa fa-ge' => 'Ge',
            'fa fa-gear' => 'Gear',
            'fa fa-gears' => 'Gears',
            'fa fa-gift' => 'Gift',
            'fa fa-git' => 'Git',
            'fa fa-github' => 'Github',
            'fa fa-github-alt' => 'Github Alt',
            'fa fa-github-square' => 'Github Square',
            'fa fa-git-square' => 'Git Square',
            'fa fa-gittip' => 'Gittip',
            'fa fa-glass' => 'Glass',
            'fa fa-globe' => 'Globe',
            'fa fa-google' => 'Google',
            'fa fa-google-plus' => 'Google Plus',
            'fa fa-google-plus-square' => 'Google Plus Square',
            'fa fa-graduation-cap' => 'Graduation Cap',
            'fa fa-group' => 'Group',
            'fa fa-hacker-news' => 'Hacker News',
            'fa fa-hand-o-down' => 'Hand O Down',
            'fa fa-hand-o-left' => 'Hand O Left',
            'fa fa-hand-o-right' => 'Hand O Right',
            'fa fa-hand-o-up' => 'Hand O Up',
            'fa fa-hdd-o' => 'Hdd O',
            'fa fa-header' => 'Header',
            'fa fa-headphones' => 'Headphones',
            'fa fa-heart' => 'Heart',
            'fa fa-heartbeat' => 'Heartbeat',
            'fa fa-heart-o' => 'Heart O',
            'fa fa-history' => 'History',
            'fa fa-home' => 'Home',
            'fa fa-hospital-o' => 'Hospital O',
            'fa fa-h-square' => 'H Square',
            'fa fa-html5' => 'Html5',
            'fa fa-image' => 'Image',
            'fa fa-inbox' => 'Inbox',
            'fa fa-indent' => 'Indent',
            'fa fa-info' => 'Info',
            'fa fa-info-circle' => 'Info Circle',
            'fa fa-inr' => 'Inr',
            'fa fa-instagram' => 'Instagram',
            'fa fa-institution' => 'Institution',
            'fa fa-italic' => 'Italic',
            'fa fa-joomla' => 'Joomla',
            'fa fa-jpy' => 'Jpy',
            'fa fa-jsfiddle' => 'Jsfiddle',
            'fa fa-key' => 'Key',
            'fa fa-keyboard-o' => 'Keyboard O',
            'fa fa-krw' => 'Krw',
            'fa fa-language' => 'Language',
            'fa fa-laptop' => 'Laptop',
            'fa fa-leaf' => 'Leaf',
            'fa fa-leanpub' => 'Leanpub',
            'fa fa-legal' => 'Legal',
            'fa fa-lemon-o' => 'Lemon O',
            'fa fa-level-down' => 'Level Down',
            'fa fa-level-up' => 'Level Up',
            'fa fa-life-bouy' => 'Life Bouy',
            'fa fa-life-ring' => 'Life Ring',
            'fa fa-life-saver' => 'Life Saver',
            'fa fa-lightbulb-o' => 'Lightbulb O',
            'fa fa-link' => 'Link',
            'fa fa-linkedin' => 'Linkedin',
            'fa fa-linkedin-square' => 'Linkedin Square',
            'fa fa-linux' => 'Linux',
            'fa fa-list' => 'List',
            'fa fa-list-alt' => 'List Alt',
            'fa fa-list-ol' => 'List Ol',
            'fa fa-list-ul' => 'List Ul',
            'fa fa-location-arrow' => 'Location Arrow',
            'fa fa-lock' => 'Lock',
            'fa fa-long-arrow-down' => 'Long Arrow Down',
            'fa fa-long-arrow-left' => 'Long Arrow Left',
            'fa fa-long-arrow-right' => 'Long Arrow Right',
            'fa fa-long-arrow-up' => 'Long Arrow Up',
            'fa fa-magic' => 'Magic',
            'fa fa-magnet' => 'Magnet',
            'fa fa-mail-forward' => 'Mail Forward',
            'fa fa-mail-reply' => 'Mail Reply',
            'fa fa-mail-reply-all' => 'Mail Reply All',
            'fa fa-male' => 'Male',
            'fa fa-map-marker' => 'Map Marker',
            'fa fa-mars' => 'Mars',
            'fa fa-mars-double' => 'Mars Double',
            'fa fa-mars-stroke' => 'Mars Stroke',
            'fa fa-mars-stroke-h' => 'Mars Stroke H',
            'fa fa-mars-stroke-v' => 'Mars Stroke V',
            'fa fa-maxcdn' => 'Maxcdn',
            'fa fa-medium' => 'Medium',
            'fa fa-medkit' => 'Medkit',
            'fa fa-meh-o' => 'Meh O',
            'fa fa-mercury' => 'Mercury',
            'fa fa-microphone' => 'Microphone',
            'fa fa-microphone-slash' => 'Microphone Slash',
            'fa fa-minus' => 'Minus',
            'fa fa-minus-circle' => 'Minus Circle',
            'fa fa-minus-square' => 'Minus Square',
            'fa fa-minus-square-o' => 'Minus Square O',
            'fa fa-mobile' => 'Mobile',
            'fa fa-mobile-phone' => 'Mobile Phone',
            'fa fa-money' => 'Money',
            'fa fa-moon-o' => 'Moon O',
            'fa fa-mortar-board' => 'Mortar Board',
            'fa fa-motorcycle' => 'Motorcycle',
            'fa fa-music' => 'Music',
            'fa fa-navicon' => 'Navicon',
            'fa fa-neuter' => 'Fa Neuter',
            'fa fa-openid' => 'Openid',
            'fa fa-outdent' => 'Outdent',
            'fa fa-pagelines' => 'Pagelines',
            'fa fa-paperclip' => 'Paperclip',
            'fa fa-paper-plane' => 'Paper Plane',
            'fa fa-paper-plane-o' => 'Paper Plane O',
            'fa fa-paragraph' => 'Paragraph',
            'fa fa-paste' => 'Paste',
            'fa fa-pause' => 'Pause',
            'fa fa-paw' => 'Paw',
            'fa fa-pencil' => 'Pencil',
            'fa fa-pencil-square' => 'Pencil Square',
            'fa fa-pencil-square-o' => 'Pencil Square O',
            'fa fa-phone' => 'Phone',
            'fa fa-phone-square' => 'Phone Square',
            'fa fa-photo' => 'Photo',
            'fa fa-picture-o' => 'Picture O',
            'fa fa-pied-piper' => 'Pied Piper',
            'fa fa-pied-piper-alt' => 'Pied Piper Alt',
            'fa fa-pied-piper-square' => 'Pied Piper Square',
            'fa fa-pinterest' => 'Pinterest',
            'fa fa-pinterest-p' => 'Pinterest P',
            'fa fa-pinterest-square' => 'Pinterest Square',
            'fa fa-plane' => 'Plane',
            'fa fa-play' => 'Play',
            'fa fa-play-circle' => 'Play Circle',
            'fa fa-play-circle-o' => 'Play Circle O',
            'fa fa-plus' => 'Plus',
            'fa fa-plus-circle' => 'Plus Circle',
            'fa fa-plus-square' => 'Plus Square',
            'fa fa-plus-square-o' => 'Plus Square O',
            'fa fa-power-off' => 'Power Off',
            'fa fa-print' => 'Print',
            'fa fa-puzzle-piece' => 'Puzzle Piece',
            'fa fa-qq' => 'Qq',
            'fa fa-qrcode' => 'Qrcode',
            'fa fa-question' => 'Question',
            'fa fa-question-circle' => 'Question Circle',
            'fa fa-quote-left' => 'Quote Left',
            'fa fa-quote-right' => 'Quote Right',
            'fa fa-ra' => 'Ra',
            'fa fa-random' => 'Random',
            'fa fa-rebel' => 'Rebel',
            'fa fa-recycle' => 'Recycle',
            'fa fa-reddit' => 'Reddit',
            'fa fa-reddit-square' => 'Reddit Square',
            'fa fa-refresh' => 'Refresh',
            'fa fa-renren' => 'Renren',
            'fa fa-reorder' => 'Reorder',
            'fa fa-repeat' => 'Repeat',
            'fa fa-reply' => 'Reply',
            'fa fa-reply-all' => 'Reply All',
            'fa fa-retweet' => 'Retweet',
            'fa fa-rmb' => 'Rmb',
            'fa fa-road' => 'Road',
            'fa fa-rocket' => 'Rocket',
            'fa fa-rotate-left' => 'Rotate Left',
            'fa fa-rotate-right' => 'Rotate Right',
            'fa fa-rouble' => 'Rouble',
            'fa fa-rss' => 'Rss',
            'fa fa-rss-square' => 'Rss Square',
            'fa fa-rub' => 'Rub',
            'fa fa-ruble' => 'Ruble',
            'fa fa-rupee' => 'Rupee',
            'fa fa-save' => 'Save',
            'fa fa-scissors' => 'Scissors',
            'fa fa-search' => 'Search',
            'fa fa-search-minus' => 'Search Minus',
            'fa fa-search-plus' => 'Search Plus',
            'fa fa-sellsy' => 'Sellsy',
            'fa fa-send' => 'Send',
            'fa fa-send-o' => 'Send O',
            'fa fa-server' => 'Fa Server',
            'fa fa-share' => 'Share',
            'fa fa-share-alt' => 'Share Alt',
            'fa fa-share-alt-square' => 'Share Alt Square',
            'fa fa-share-square' => 'Share Square',
            'fa fa-share-square-o' => 'Share Square O',
            'fa fa-shield' => 'Shield',
            'fa fa-ship' => 'Ship',
            'fa fa-shirtsinbulk' => 'Shirtsinbulk',
            'fa fa-shopping-cart' => 'Shopping Cart',
            'fa fa-signal' => 'Signal',
            'fa fa-sign-in' => 'Sign In',
            'fa fa-sign-out' => 'Sign Out',
            'fa fa-simplybuilt' => 'Simplybuilt',
            'fa fa-sitemap' => 'Sitemap',
            'fa fa-skyatlas' => 'Skyatlas',
            'fa fa-skype' => 'Skype',
            'fa fa-slack' => 'Slack',
            'fa fa-sliders' => 'Sliders',
            'fa fa-smile-o' => 'Smile O',
            'fa fa-sort' => 'Sort',
            'fa fa-sort-alpha-asc' => 'Sort Alpha Asc',
            'fa fa-sort-alpha-desc' => 'Sort Alpha Desc',
            'fa fa-sort-amount-asc' => 'Sort Amount Asc',
            'fa fa-sort-amount-desc' => 'Sort Amount Desc',
            'fa fa-sort-asc' => 'Sort Asc',
            'fa fa-sort-desc' => 'Sort Desc',
            'fa fa-sort-down' => 'Sort Down',
            'fa fa-sort-numeric-asc' => 'Sort Numeric Asc',
            'fa fa-sort-numeric-desc' => 'Sort Numeric Desc',
            'fa fa-sort-up' => 'Sort Up',
            'fa fa-soundcloud' => 'Soundcloud',
            'fa fa-space-shuttle' => 'Space Shuttle',
            'fa fa-spinner' => 'Spinner',
            'fa fa-spoon' => 'Spoon',
            'fa fa-spotify' => 'Spotify',
            'fa fa-square' => 'Square',
            'fa fa-square-o' => 'Square O',
            'fa fa-stack-exchange' => 'Stack Exchange',
            'fa fa-stack-overflow' => 'Stack Overflow',
            'fa fa-star' => 'Star',
            'fa fa-star-half' => 'Star Half',
            'fa fa-star-half-empty' => 'Star Half Empty',
            'fa fa-star-half-full' => 'Star Half Full',
            'fa fa-star-half-o' => 'Star Half O',
            'fa fa-star-o' => 'Star O',
            'fa fa-steam' => 'Steam',
            'fa fa-steam-square' => 'Steam Square',
            'fa fa-step-backward' => 'Step Backward',
            'fa fa-step-forward' => 'Step Forward',
            'fa fa-stethoscope' => 'Stethoscope',
            'fa fa-stop' => 'Stop',
            'fa fa-street-view' => 'Street View',
            'fa fa-strikethrough' => 'Strikethrough',
            'fa fa-stumbleupon' => 'Stumbleupon',
            'fa fa-stumbleupon-circle' => 'Stumbleupon Circle',
            'fa fa-subscript' => 'Subscript',
            'fa fa-subway' => 'Fa Subway',
            'fa fa-suitcase' => 'Suitcase',
            'fa fa-sun-o' => 'Sun O',
            'fa fa-superscript' => 'Superscript',
            'fa fa-support' => 'Support',
            'fa fa-table' => 'Table',
            'fa fa-tablet' => 'Tablet',
            'fa fa-tachometer' => 'Tachometer',
            'fa fa-tag' => 'Tag',
            'fa fa-tags' => 'Tags',
            'fa fa-tasks' => 'Tasks',
            'fa fa-taxi' => 'Taxi',
            'fa fa-tencent-weibo' => 'Tencent Weibo',
            'fa fa-terminal' => 'Terminal',
            'fa fa-text-height' => 'Text Height',
            'fa fa-text-width' => 'Text Width',
            'fa fa-th' => 'Th',
            'fa fa-th-large' => 'Th Large',
            'fa fa-th-list' => 'Th List',
            'fa fa-thumbs-down' => 'Thumbs Down',
            'fa fa-thumbs-o-down' => 'Thumbs O Down',
            'fa fa-thumbs-o-up' => 'Thumbs O Up',
            'fa fa-thumbs-up' => 'Thumbs Up',
            'fa fa-thumb-tack' => 'Thumb Tack',
            'fa fa-ticket' => 'Ticket',
            'fa fa-times' => 'Times',
            'fa fa-times-circle' => 'Times Circle',
            'fa fa-times-circle-o' => 'Times Circle O',
            'fa fa-tint' => 'Tint',
            'fa fa-toggle-down' => 'Toggle Down',
            'fa fa-toggle-left' => 'Toggle Left',
            'fa fa-toggle-right' => 'Toggle Right',
            'fa fa-toggle-up' => 'Toggle Up',
            'fa fa-train' => 'Train',
            'fa fa-transgender' => 'Transgender',
            'fa fa-transgender-alt' => 'Transgender Alt',
            'fa fa-trash-o' => 'Trash O',
            'fa fa-tree' => 'Tree',
            'fa fa-trello' => 'Trello',
            'fa fa-trophy' => 'Trophy',
            'fa fa-truck' => 'Truck',
            'fa fa-try' => 'Try',
            'fa fa-tumblr' => 'Tumblr',
            'fa fa-tumblr-square' => 'Tumblr Square',
            'fa fa-turkish-lira' => 'Turkish Lira',
            'fa fa-twitter' => 'Twitter',
            'fa fa-twitter-square' => 'Twitter Square',
            'fa fa-umbrella' => 'Umbrella',
            'fa fa-underline' => 'Underline',
            'fa fa-undo' => 'Undo',
            'fa fa-university' => 'University',
            'fa fa-unlink' => 'Unlink',
            'fa fa-unlock' => 'Unlock',
            'fa fa-unlock-alt' => 'Unlock Alt',
            'fa fa-unsorted' => 'Unsorted',
            'fa fa-upload' => 'Upload',
            'fa fa-usd' => 'Usd',
            'fa fa-user' => 'User',
            'fa fa-user-md' => 'User Md',
            'fa fa-user-plus' => 'User Plus',
            'fa fa-users' => 'Users',
            'fa fa-user-secret' => 'User Secret',
            'fa fa-user-times' => 'User Times',
            'fa fa-venus' => 'Venus',
            'fa fa-venus-double' => 'Venus Double',
            'fa fa-venus-mars' => 'Venus Mars',
            'fa fa-viacoin' => 'Viacoin',
            'fa fa-video-camera' => 'Video Camera',
            'fa fa-vimeo-square' => 'Vimeo Square',
            'fa fa-vine' => 'Vine',
            'fa fa-vk' => 'Vk',
            'fa fa-volume-down' => 'Volume Down',
            'fa fa-volume-off' => 'Volume Off',
            'fa fa-volume-up' => 'Volume Up',
            'fa fa-warning' => 'Warning',
            'fa fa-wechat' => 'Wechat',
            'fa fa-weibo' => 'Weibo',
            'fa fa-weixin' => 'Weixin',
            'fa fa-whatsapp' => 'Whatsapp',
            'fa fa-wheelchair' => 'Wheelchair',
            'fa fa-windows' => 'Windows',
            'fa fa-won' => 'Won',
            'fa fa-wordpress' => 'Wordpress',
            'fa fa-wrench' => 'Wrench',
            'fa fa-xing' => 'Xing',
            'fa fa-xing-square' => 'Xing Square',
            'fa fa-yahoo' => 'Yahoo',
            'fa fa-yen' => 'Yen',
            'fa fa-youtube' => 'Youtube',
            'fa fa-youtube-play' => 'Youtube Play',
            'fa fa-youtube-square' => 'Youtube Square',
            'flaticon-man' => 'flaticon-man',
            'flaticon-transport-3' => 'flaticon-transport-3',
            'flaticon-camp' => 'flaticon-camp',
            'flaticon-transport-2' => 'flaticon-transport-2',
            'flaticon-transport-3' => 'flaticon-transport-3',
        );
        return $icon;
    }

}


/**
 * Save Meta options
 * @return 
 */
if (!function_exists('soccer_save_meta_data')) {

    function soccer_save_meta_data($post_id = '') {
        if (!is_admin()) {
            return;
        }

        if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
            return;
        }
		
		// Save Slider
        if (get_post_type() == 'tg_slider') {
            if (!function_exists('fw_get_db_post_option')) {
                return;
            }
            $data_shortcode = '[soccer_slider id="' . $post_id . '"]';
            if (isset($_POST['fw_options'])) {
                update_post_meta($post_id, 'soccer_shortcode', $data_shortcode); //exit;
            }
        }

        //Fixure date
        if (get_post_type() == 'tg_fixture') {
            if (!function_exists('fw_get_db_post_option')) {
                return;
            }
            
            if (!empty($_POST['fw_options'])) {
                foreach ( $_POST['fw_options'] as $key => $value ) {
                    update_post_meta($post_id, $key, $value); //exit;
                    if( $key === 'date_match' ){
                       update_post_meta($post_id, $key.'_string', strtotime($value)); //exit;
                    }
                }
            }
        }
    }
    add_action('save_post', 'soccer_save_meta_data');

}